### ISSUE TITLE
Error On Server Startup

### ISSUE THREAD

**Issue by AnZaNaMa** [UnRealDinnerbone/Yarm#12]
Whenever I start up a server with this mod in it, it crashes. Looks like you're trying to register models on server-side as well as client.

http://pastebin.com/sKCDtGYa

**Comment by UnRealDinnerbone** [comment]
Update Yarm to 3.7.1 and also updated bookshelf mod as that is the mod the is crashing you. Also you may not need the bookshelf mod anymore as i not longer require it for my mod to work.

**Comment by UnRealDinnerbone** [comment]
Ok there was a bug the did make the server crash but not in that case so i fixed it
